[package]
name = "book-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
open-library = { path = "../.." }
structopt = "0.3.23"

[dependencies.tokio]
version = "1.11.0"
features = ["macros", "rt-multi-thread"]
