on:
  push:
    tags:
      - 'v*'
name: Release

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

  build-release:
    name: Release Build
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Cargo Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token "${{secrets.crates_token}}"
